# 参考链接 https://hub.docker.com/_/mongo
version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: &username root
      MONGO_INITDB_ROOT_PASSWORD: &password 123456

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 50091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: *username
      ME_CONFIG_MONGODB_ADMINPASSWORD: *password
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo:27017/
