# 暂时未验证
version: "3.8"
services:
  mqnamesrv:
    image: apache/rocketmq:5.1.3
    container_name: mqnamesrv
    ports:
      - 50700:9876
    restart: always
    privileged: true
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
    command: ["sh", "mqnamesrv"]
  mqbroker:
    image: apache/rocketmq:5.1.3
    container_name: mqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
      - 8081:8081
      - 8080:8080
      - 8082:8082
    restart: always
    privileged: true
    depends_on:
      - "mqnamesrv"
    environment:
      - NAMESRV_ADDR=mqnamesrv:9876
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=256M
    command: ["sh", "mqbroker", "--enable-proxy"]
  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rocketmq-dashboard
    ports:
      - 50790:8080
    restart: always
    privileged: true
    depends_on:
      - "mqnamesrv"
      - "mqbroker"
    environment:
      - JAVA_OPTS= -Xmx256M -Xms256M -Xmn128M -Drocketmq.namesrv.addr=mqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
